### PR TITLE
Updated Nuget package dependencies

### PR DESCRIPTION
**Pull request by ca-ta**
- Microsoft.Data.*; System.Spatial  -> 5.6.4
- Newtoinsoft.Json -> 6.0.8
- Microsoft.WindowsAzure.ConfigurationManager -> 3.1.0

### CODE REVIEW

**Comment by ca-ta** [comment]
Thanks for merging!

**Comment by garvincasimir** [comment]
Thank you for contributing. I would love to learn about how you are using
the project.

**Comment by ca-ta** [comment]
You know.. for search ;-)

We're hitting the PAAS Elasticsearch cluster from an Orleans cluster, over an internal balanced endpoint. Related to [this](http://www.experiad.com) (the site is a bit dated, but should give you an idea of what we're doing). The actual system is not public at this time - I can ping you when it does become public, if you want me to)

**Comment by garvincasimir** [comment]
That is really awesome. Exact situation I thought it would work great in.
Yes I would definitely appreciate a ping when you release or have any
advice as you put this into production.

**Comment by ca-ta** [comment]
Will do - thank you for open sourcing the project!

**Pull request merged**
