### PR TITLE
Exploratory: moving to paket for package management (+ updated packages)

### PR DESCRIPTION
**Pull request by ca-ta**
Hi Garvin,

First, thank you for this - it works wonderfully!

I've had to update the package dependencies in order to make ```Elasticsearch-Azure-PAAS```  work with my current projects (we're using ```Microsoft.WindowsAzure.ConfigurationManager``` 3.1.0 across, and it is incompatible with 2.x - they changed the namespace from ```WindowsAzure``` to ```Azure```, go figure).

While at it, I've realized that:

1. The projects in ```Elasticsearch-Azure-PAAS```  were actually referencing various package versions. For example, ```ElasticsearchRole/packages.config``` was referencing version 5.6.2 of ```Microsoft.Data.*``` and version 5.0.8 of , ```Newtonsoft.Json``` while ```Worker.Common/packages.config``` was referencing version 5.6.3 and 6.0.6 respectively.
  * This is a fairly common - and most times unintended - occurrence when using Nuget, one I think undesirable in most scenarios.
2. The repo does not contain a quick way to generate the Nuget package.
3. installing the Nuget package clobbers any customized Yml config files (for example, I changed discovery.zen.minimum_master_nodes).

In order to try and address the above, I am proposing to switch the package management to [Paket](http://fsprojects.github.io/Paket/). This addresses 1. and 2.(2. is addressed by the ```Elasticsearch-Azure-PAAS.paket.template```). In order to generate the package, one could  execute ```.paket\paket pack output.``` at the command line.

This is an exploratory pull request, trying to address the above, and has some shortcomings:
* Not including the configuration files as content would require some additional instructions
* I have not included the powershell scripts (command line tools - like Paket - don't run them at package install time anyway). I'm also guilty of not having given them a proper look.
* The version in ```Elasticsearch-Azure-PAAS.paket.template``` is bogus - you will want to change it. 

Let me know what you think (of course, no offense taken if you think this isn't a good fit). Cheers!

### CODE REVIEW

**Comment by garvincasimir** [comment]
Hi @ca-ta I am happy that you find the project useful and thank you for taking the time to submit a pull request. Let me start by responding to your numbered points.

1.  I honestly have not paid as much attention to package versions as I probably should. One thing to note is that Worker.Common is the only project included in the distributed package. The cloud project is in this solution to aid in development. That being said I agree that we should make the versions consistent. But, let's do it in a separate pull. I can merge that once i see it.

2. I figured I would be the only one creating the NuGet package so I didn't put too much effort into easily generating the package. The challenge here is the NuGet package is in a separate repo. I assume we can use git submodules to pull it in? I am open to suggestions.

3. I was under the impression that NuGet skips existing files. I need to do some testing in that regard. I am seriously considering making the config files downloadable just like the other artifacts so maybe that will solve that issue anyway.

I am not familiar with packet so I would have to read up on it first. This may be a silly question but is there any reason why we can't have both Packet and NuGet? The distributed package is simply the Worker.Common assembly, the installation powershell scripts and the config file templates. We can easily create a separate repo for the packet package. I like to think of dependency management as a separate concern. 

The installation powershell script is not absolutely necessary but helps with the initial setup by adding all the config settings to the service definition and configuration files in your cloud project.

**Comment by ca-ta** [comment]
Hi Garvin, thanks for answering so quickly!

Let's keep the point-based format - it's nice and clear:
 1. Yes, I am aware that Worker.Common is the only project included in the package - . I've actually addressed the inconsistencies *by migrating to Paket* - Paket's package versioning strategy is different than Nuget's and makes this type of housekeeping trivial (the main reason I am using Paket these days rather than Nuget). So I guess this pull *is* the pull to look at. The reason you are seeing so many changes is because Paket tags references added from Nuget packages to the project files - so the project files have changed quite dramatically.
 2. I guess there are a couple of sub-points to consider:
  * Your being the only one to push new packages to Nuget,Org make sense. That being said, it's handy for someone else to be able to create Nuget packages as well - if only for deploying packages that contain changes made on their own fork to a local nugget repository. I find this useful when I need to make progress on a project before an official updated package is released. Case in point, I am currently using a local nugget package, generated from my branch of  ```Elasticsearch-Azure-PAAS```, in order to address my need for updated dependencies. 
  * I'm probably missing the point, but why do you need a separate repo for the NuGet package? I tend to think about nuget packages as build output. I would imagine that we could include the necessary powershell scripts, etc. in the current repo, and then generate the Nuget package as a build step. Generating the package is trivial with Paket and we do not need to pull in the nuget package itself - that's why I've included ``` Elasticsearch-Azure-PAAS.paket.template ``` in the pull request. Check [this](http://fsprojects.github.io/Paket/template-files.html) out.
 3. It may be that Paket and Nuget work differently in this respect - Paket tracks content files included from nuget packages and replaces any existing content (modified or not). I think this approach makes sense, as there is no way to know whether the old/modified content is compatible with the new one (think for the sake of argument that the content is made up of a bunch of inter-dependent Javascript files).
  * Making the config files downloadable may indeed be the way to go:
    * One could easily have different configurations for local and cloud settings (especially seeing how MS is dropping the full emulator, one could benefit from tweaking settings such as number of master nodes, replicas, etc.).
    * no more worrying about the ```config``` folder
    * one would need to ensure that the system has good defaults in the absence of a configuration file (default Elasticsearch behavior could suffice, but I haven't thought about this in detail)
    * As an aside, I've experimented with programmatic configuration a few months back, when the Nuget package was not available, but only for some specific settings - having downloadable config files may be better/simpler/sufficient.
 4. Paket is just a nuget package manager - so there are no "paket" packages, it works with (and generates) nuget packages. So it's an either/or, really - give it a look and let's talk once you've formed an opinion. I personally like it * a lot*. I've stumbled upon it after I've switched to F# as my go-to .Net language, and haven't looked back.
  * Clone my branch to see how it all works - I've also added a batch file to show how easy it is to generate the nuget package.
 5. About the powershell scripts - Indeed, right now the role fails to start if any of the required settings is missing - I am inclined to think that (excluding some absolutely necessary settings - such as the file URLs) it may be better to address this by falling back to sane, documented defaults. No more powershell ...

**Comment by garvincasimir** [comment]
1. Thanks for explaining why there are so many changes. I did a quick review of packet and it seems fine but I don't see a huge advantage over NuGet for this project.  We can easily fix the dependency versions without changing over to another package manager. I am thinking it is best to stick with the more dominant option in the absence of any significant gains.
2. I agree that you can consider nuget packages to be build output. I am open to including it in the main project if it is more useful that way.
3. I disagree with having the package replace files. Why would you purposely include it in your project only to have it replaced by a package? If you wanted to have the replacement file you can always delete yours manually. What happens during a package update? Aren't you guaranteed to have customized files then?
4. I have not had a chance but will try packet in your repo.
5. I think providing the install script for adding initial settings is critical. One of my goals is for someone to go through as few steps as possible to get the project running. I prefer starting of with a default config over having magic values embedded in the code. Less control logic and more transparency.Also, adding these settings to the config file can be very tedious. I am confused because you said that packet creates NuGet packages. If it does, why is there an issue with the install script?

**Comment by ca-ta** [comment]
1. OK - It is true that for a project of this size the benefits may not be worth moving off Nuget and losing familiarity. Yes, the dependency versions can be updated/synchronized. 
2. That would be great - having a way to generate the Nuget package from the current repo would definitely be helpful.
3. I don't remember how Nuget handles these cases - you may want to verify that it indeed leaves the modified files untouched. In the case of Paket, I have re-checked and the modified files are indeed replaced. This turns out to not be a big deal if one checks what has changed as a result of a package update (say, against the latest check-in) and merges the changes one wants to keep (or simply undoes the changes made to customized files, if so warranted). I find it more dangerous to be unaware that the package content has changed (which can easily happen if the customized files are simply skipped). Again, this may not directly apply to projects where the content is trivial, but I think it is a valid approach for any packages that inject more complex content in the project.
4. OK - thanks for willing to give it a try.
5. The issue is not with including the powershell scripts in the package, that would work just fine. You can definitely use Paket to include the scripts in the package - so no problem there (that is , the switch to Paket can be done without any impact on the Nuget package's consumers). The issue with powershell is about *automatically* running the .ps1 scripts at package install time - see [this](http://fsprojects.github.io/Paket/faq.html#Does-Paket-run-install-ps1-scripts). I can't stop thinking that the powershell scripts also qualify as magic - something that alters one's project in ways that are not necessarily obvious (as opposed to simply adding content files). That being said, the default config approach currently in place works for me and changing it really isn't on my radar at the moment.

I understand that moving to Paket may be too disruptive and I am cool with closing this pull request. I can submit a dependency update pull request afterwards (one that simply modifies the packages.config and app.config files) if that's OK.

**Comment by garvincasimir** [comment]
1. Agreed - A separate pull request to handle dependences. NuGet will remain as the package manager.
2. Agreed - Move NuGet package to main repo
3. if the package manager deletes your file there really isn't a straight forward option to diff/merge. Is there? You can't just merge a deleted file.
5. I read the link you sent on this and I think there is merit to Packet's philosophy. That pretty much is a nice way of saying "Tell your users to go RTFM before using your library". If I am searching for a solution and I find a library with10 manual setup steps then I find  another which auto configures itself, I would probably end up going with the one I can get running quicker. Think about it, you asked for the NuGet package to be in the same repo so it can be built automatically. The alternative is simply copying the dll over to the lib folder, manually updating the version number and running the generate package command. Just 3 steps.Yes, NuGet packages can make crazy changes to your files but you can easily see those changes in your diff.

**Comment by ca-ta** [comment]
1. OK, I'll submit a pull request shortly - thanks!
2. Cool - I understand you will be the one making this change - thanks!
3. The assumption that I made (I think the same one you made in your answer to point 4) was that the package update takes place on a clean branch (that is, everything has been committed into say, Git, and there are no local changes). In this case: 
  * If the package manager deletes your file, there *is* nothing to diff/merge in regards to that specific file - you just have to decide if you still want the file - whether to undo the change or not. 
  * If the package manager *overwrites* your file (as it happens in the case of the yaml settings), then of course you can diff/merge.
4. About choosing the easier to use lib: maybe, choosing a library depends on more than just that - and we're really talking about 1 manual step. 
 * I do not agree that copying the dll is a real alternative - a nuget package can be placed in a repository and automatically pulled during build (the alternative would be to check in the dll - I wouldn't want to do that). 
 * Out of the 55 nuget packages in use by a fairly large project I'm working on, the only other package that has an install.ps1 script is Newtonsoft.Json - and that script has to do with displaying a splash window during install, so it's just a nicety. I know this doesn't mean that there is no use case for powershell install scripts, but it's an indication that it is a narrow one (I suspect it has to do with taking a dependency on Visual Studio, and that is probably perceived as too constraining).
* I haven't looked at the powershell scripts in detail - I am thinking that one added complexity with such scripts is making sure that, for example, installing a new version of the package does not overwrite existing/modified settings.

I'll shut up now and close the darn pull request :-) - thanks for having taken the time to discuss it!

**Comment by garvincasimir** [comment]
The NuGet package is now part of the main repository. It automatically creates the package when you build using post build events.

**Comment by ca-ta** [comment]
Super - Thanks!

**Pull request closed without merging**
